### ISSUE TITLE
Watch Video about MEV

### ISSUE THREAD

**Issue by RusseII** [Bookcliff/learning#12]
https://www.youtube.com/watch?v=UZ-NNd6yjFM

**Comment by Bookcliff** [comment]
Front running: Using the open source nature of smart contracts to know what contracts will be added to the next block and capitalizing off of it (e.g., using someone else's solution with a slightly higher gas fee to make sure your block is mined before the person that originally came up with the solution - but since you were added to the block first, you get the rewards)
